---
- name: Check if node exporter exist
  stat:
    path: "/usr/local/bin/node_exporter"
  register: __check_node_exporter_present

- name: Create the node_exporter group
  group:
    name: "node_exporter_user"
    state: present
    system: true

- name: Create node exporter user
  user:
    name: "node-exporter"
    group: "node_exporter_user"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: Create node exporter config dir
  file:
    path: "/etc/node_exporter"
    state: directory
    owner: "node-exporter"
    group: "node_exporter_user"

- name: If node exporter exist get version
  shell: "cat /etc/systemd/system/node_exporter.service | grep Version | sed s/'.*Version '//g"
  when: __check_node_exporter_present.stat.exists == true
  changed_when: false
  register: __get_node_exporter_version
  
- name: Download and unzip node exporter if not exist
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    validate_certs: no

- name: Move the binary to the final destination
  copy:
    src: "/tmp/node_exporter-1.1.2.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "node-exporter"
    group: "node_exporter_user"
    mode: 0755
    remote_src: yes

- name: Clean
  file:
    path: /tmp/node_exporter-1.1.2.linux-amd64/
    state: absent

- name: Install service
  template:
    src: templates/ne/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0755

- name: Service always started
  systemd:
    name: node_exporter
    state: started
    enabled: yes

- name: Reload_daemon_and_restart_node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
