---
- name: Create User Alertmanager
  user:
    name: alertmanager
    create_home: no
    shell: /bin/false

- name: Create Directories For Alertmanager
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
  loop:
    - '/tmp/alertmanager'
    - '/etc/alertmanager'
    - '/var/lib/prometheus/alertmanager'

- name: Download And Unzipped Alertmanager
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.24.0/alertmanager-0.24.0.linux-amd64.tar.gz
    dest: /tmp/alertmanager
    creates: /tmp/alertmanager/alertmanager-0.24.0.linux-amd64
    remote_src: yes

- name: Copy Bin Files From Unzipped to Alertmanager
  copy: 
    src: /tmp/alertmanager/alertmanager-0.24.0.linux-amd64/{{ item }}
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve
    owner: alertmanager
    group: alertmanager
  loop: [ 'alertmanager', 'amtool' ]

- name: Copy Conf File From Unzipped to Alertmanager
  copy: 
    src: /tmp/alertmanager/alertmanager-0.24.0.linux-amd64/alertmanager.yml
    dest: /etc/alertmanager/
    remote_src: yes
    mode: preserve
    owner: alertmanager
    group: alertmanager

- name: Create File for Alertmanager Systemd
  template:
    src=templates/alertmanager/alertmanager.service
    dest=/etc/systemd/system/

- name: Create conf fot Alertmanager
  template:
    src=templates/alertmanager/alertmanager.yml
    dest=/etc/alertmanager

- name: Systemctl Alertmanager Start
  systemd:
    name: alertmanager
    state: started
    enabled: yes

- name: Install new nginx config file
  template:
    src: templates/alertmanager/nginx.conf.j2
    dest: /etc/nginx/sites-available/alertmanager.devops-lso.ru
    mode: '644'
    backup: yes

- name: Put reverse proxy site config in enabled
  become: yes
  file:
    src: /etc/nginx/sites-available/alertmanager.devops-lso.ru
    dest: /etc/nginx/sites-enabled/alertmanager.devops-lso.ru
    state: link

- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Reload nginx service
  become: yes
  service:
    name: nginx
    state: reloaded
    enabled: yes

- name: Stop nginx
  service:
    name: nginx
    state: stopped

- name: Start nginx
  service:
    name: nginx
    state: started
