---
- name: Update and install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Prometheus configuration file
  template:
    src: templates/prometheus/prometheus.j2
    dest: "/etc/prometheus/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus

- name: Start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes

- name: Restart_prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Install new nginx config file
  template:
    src: templates/prometheus/nginx.conf.j2
    dest: /etc/nginx/sites-available/prometheus.devops-lso.ru
    mode: '644'
    backup: yes

- name: Put reverse proxy site config in enabled
  become: yes
  file:
    src: /etc/nginx/sites-available/prometheus.devops-lso.ru
    dest: /etc/nginx/sites-enabled/prometheus.devops-lso.ru
    state: link

- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Reload nginx service
  become: yes
  service:
    name: nginx
    state: reloaded
    enabled: yes

- name: Stop nginx
  service:
    name: nginx
    state: stopped

- name: Start nginx
  service:
    name: nginx
    state: started
