---
- name: Install prerequisites
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - openssh-server
    - ca-certificates

- name: Check if GitLab-CE is already installed
  stat:
    path: /etc/gitlab
  register: gitlab

- name: Download GitLab-CE Deb script
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/gitlab-ce.deb.sh
    mode: '644'
  when: not gitlab.stat.exists

- name: Uncomment a line os
  lineinfile: 
    path: /tmp/gitlab-ce.deb.sh
    regexp: '(.*)$os="(.*)$'
    line: 'os="ubuntu"'

- name: Uncomment a line dist
  lineinfile: 
    dest: /tmp/gitlab-ce.deb.sh
    regexp: '^(.*)dist="(.*)$'
    line: 'dist="focal"'

- name: Execute GitLab-CE Deb script
  command: /bin/bash /tmp/gitlab-ce.deb.sh
  when: not gitlab.stat.exists

- name: Install GitLab-CE
  package:
    name: gitlab-ce
    state: latest

- name: Configure GitLab-CE
  command: gitlab-ctl reconfigure

- name: Install prerequisites
  package:
    name: dnsutils
    state: latest

- name: Change port of Gitlab-CE
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^external_url'
    backrefs: yes
    line: "external_url 'http://192.168.101.14:8082'"
    state: present
  register: gitlabport

- name: Reconfigure Gitlab-CE
  command: gitlab-ctl reconfigure

- name: Install new nginx config file
  template:
    src: templates/gitlab/nginx.conf.j2
    dest: /etc/nginx/sites-available/gitlab.devops-lso.ru
    mode: '644'
    backup: yes

- name: Put reverse proxy site config in enabled
  become: yes
  file:
    src: /etc/nginx/sites-available/gitlab.devops-lso.ru
    dest: /etc/nginx/sites-enabled/gitlab.devops-lso.ru
    state: link

- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Reload nginx service
  become: yes
  service:
    name: nginx
    state: reloaded
    enabled: yes

- name: Stop nginx
  service:
    name: nginx
    state: stopped

- name: Start nginx
  service:
    name: nginx
    state: started
